mysite/jampredict/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from jampredict import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    url(r'^dymap$', 'jampredict.views.dymap', name='dymap'),
    url(r'^$', 'jampredict.views.index', name='home'),
)

mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    url(r'^', include('jampredict.urls', namespace='jampredict')),

    url(r'^admin/', include(admin.site.urls)),
)

mysite/jampredict/models.py
from django.db import models

# Create your models here.

mysite/jampredict/views.py
#coding=utf-8

from django.shortcuts import render
from math import floor
import json
import csv
import time
import datetime
import pdb
import requests


def cyyadd(s, v):
    d = int(s)
    d = d + v
    if d < 0:
        d = 0
    return "%02d" % d


# Create your views here.
def index(request):
    return render(request, 'jampredict/index.html')

def dymap(request):
    dx = 40
    dy = 40
    with open("jampredict/data/SensorMap.json") as f:
        data = json.loads(f.read())


    with open("jampredict/data/viewinfo.json") as f:
        viewinfo = json.loads(f.read())

    with open("jampredict/data/map.json") as f:
        gridmap = f.read()
        gridmap = json.loads(gridmap)

    # with open("jampredict/data/data.csv") as f:
    #     csvdata = csv.reader(f)
    #     my_list = list(csvdata)
    #     my_dic = {}
    #     for row in my_list:
    #         my_dic[row[0]] = row[1:]

    # getting speed data from server
    querytime = None
    gettime = ''
    if 'time' in request.GET:
        gettime = request.GET['time']
        # 2015/05/22 21:52
        year = gettime[0:4]
        month = gettime[5:7]
        day = gettime[8:10]
        hour = gettime[11:13]
        minute = gettime[14:16]
        minute1 = cyyadd(minute, -2)
        minute2 = cyyadd(minute, 2)
        s1 = hour + ':' + minute1
        s2 = hour + ':' + minute2

        querytime = year + '-' + month + '-' + day + '/' + s1 + '/' + s2


    else:
        # querytime = '2015-05-21/00:00/00:06'
        querytime = ''

    if 'type' in request.GET:
        gettype = request.GET['type']
        if gettype == 'real':
            querytype = 'getRealSpeed/'
            querytype_ch = "實際車流"
        elif gettype == 'mlpredict':
            querytype = 'getPredictSpeed/'
            querytype_ch = 'ML車流預測'

        elif gettype == 'spredict':
            querytype = 'getStatisticSpeed/'
            querytype_ch = '統計車流預測'
    else:
        querytype = 'getRealSpeed/'
        querytype_ch = ""
        gettype = "real"

    if querytime == '':
        jdic = {'SectionData': []}
    else:
        req = requests.get('http://140.96.178.6:8080/' + querytype + querytime)
        jdic = json.loads(req.text)
    jarr = jdic['SectionData']
    my_dic = {item['SectionId']: item for item in jarr}

    # merge speed information into SensorMap data
    # if no sped information for the sensor, then assign -1
    for item in data:
        if not item['SectionId'] in my_dic:
            item['AvgSpd'] = -1
        else:
            item['AvgSpd'] = my_dic[item['SectionId']]['AvgSpd']

    for item in data:
        sid = item['SectionId']
        if sid in my_dic:
          my_dic[sid]['HighWay'] = item['HighWay']

    cmap = [[-1 for _ in range(dy)] for _ in range(dx)]
    for i in xrange(0, dx):
        for j in xrange(0, dy):
            cell = gridmap[i][j]
            if len(cell) is 0:
                continue
            sum = 0
            count = 0
            for item in cell:
                # my_dic[item][1] to get velocity of item
                if item in my_dic.keys() and my_dic[item]['AvgSpd'] != '-1':
                    spd = float(my_dic[item]['AvgSpd'])
                    if gettype == 'real':
                        spd = spd / 3
                    if my_dic[item]['HighWay'] == '1':
                        spd = spd * 0.6
                    sum += spd
                    count = count + 1
            if count is not 0:
                v = float(sum) / count
                cmap[i][j] = v

    return render(request, 'jampredict/dymap.html',
                  {'data': json.dumps(data), 'cmap': json.dumps(cmap),
                   'time': gettime, 'type':gettype,  'type_ch': querytype_ch,
                   'viewinfo': json.dumps(viewinfo)})

mysite/jampredict/templates/jampredict/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>估估出門好時機</title>

    <!-- Bootstrap -->
    <link href='{% static "bootstrap/css/bootstrap.min.css" %}' rel="stylesheet">
    <link href='{% static "jampredict/css/jampredict.css" %}' rel="stylesheet">
    <link rel="stylesheet" href="{% static "bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" %}" />

    {% block "extra_style"%}
    {% endblock %}
    <style type="text/css" media="screen">
      /* html { height: 100% }
      body { height:100%;  background:#eee; margin:1em; text-align:center; }
      /*  body { height: 100%; margin: 0; padding: 0 } */
    </style>
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDErdk4TToHeg_NnDslstsd5z5Son5spuE&sensor=FALSE">
    </script>
  </head>
  <body> 
    {% block "body_content" %}
    {% endblock %}
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
    <script type="text/javascript" src="{% static "bower_components/moment/min/moment.min.js" %}"></script>
    <!--script type="text/javascript" src="{% static "bower_components/bootstrap/dist/js/bootstrap.min.js"%}"></script-->
    <script type="text/javascript" src="{% static "bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js" %}"></script>
    <script type="text/javascript">
    {% block "extra_script" %}
    {% endblock %}
    </script>
    </body>
  </html>

mysite/jampredict/templates/jampredict/dymap.html
{% extends "jampredict/base.html" %}
{% load staticfiles %}
{% block "body_content" %} 

<div class="container-fluid" >
  <div class='cyynavi row' style='background-image: url("{% static 'jampredict/images/web_head.png'%}")'>
    <div class='mycontainer'>
      <h1>台北市車流量預測地圖 <small>Taipei Traffic Prediction Map</small></h1>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 id='message' class="panel-title">使用資訊:</h3>
    </div>
    <div  id='message-block' class="panel-body">
      <ul class="list-group">
        <li class="list-group-item">此系統無實作防呆,充滿bug</li>
        <li class="list-group-item">我們僅蒐集5/15 - 5/23資料</li>
        <li class="list-group-item">目前已知bug: 實際時間選當下可能會無結果</li>
        <li class="list-group-item">預測目前僅能顯示隔天, 此部分是因為debug過程中演算法時有調整, 預測太多天會造成debug花費時間很長 </li>
        <li class="list-group-item">請小心輕放ＱＱ</li>
      </ul>
    </div>
  </div>

  <div class='row mycontainer'>
    <div class='col-xs-6 col-sm-8 col-md-9 left_panel'>
      <div id="map_canvas" class="" style=""> OOPS!!!!</div>
    </div>
    <div class='col-xs-6 col-sm-4 col-md-3  right_panel'>

      <div class='center'>
        <img id='weather' src="{% static 'jampredict/images/sunny.png'%}" alt="今天天氣" style="width:200px;height:200px" class='center hidden'>
        <h3>資料時間: {{time}}</h3>
        <h3>資料類型: {{type_ch}}</h3>
      </div>


      <div class='color-indicator'>
        <div class='row'>
          <div class='col-xs-2 text'>
            暢通
          </div>
          <div class ='col-xs-8 color-bar'>
          </div>
          <div class='col-xs-2 text'>
            擁塞
          </div>
        </div>
        <div class='row'>
          <div class='form-group col-xs-offset-2'>
            <div class='checkbox-inline'>
              <input id="cbx1" type="checkbox" value="1"> 顯示監測點
            </div>
            <div class='checkbox-inline'>
              <input id="cbx2" type="checkbox" value="1"> 顯示景點
            </div>
          </div>
        </div>
      </div>
      <form action='{% url "jampredict:dymap" %}' method='get'>
        <div class="form-group">
          <div class="radio-inline">
            <label>
              <input type="radio" name="type" id="type1" value="real">
              實際車流         
            </label>
          </div>

          <div class="radio-inline">
            <label>
              <input type="radio" name="type" id="type2" value="spredict" >
              統計車流預測        
            </label>
          </div>

          <div class="radio-inline">
            <label>
              <input type="radio" name="type" id="type3" value="mlpredict">
              ML車流預測
            </label>
          </div>
        </div>
        <div class="row">
          <div class='col-sm-12'>
            <div class="form-group">
              <div class='input-group date' id='datetimepicker1'>
                <input type='text' class="form-control" name='time' required/>
                <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
                </span>
              </div>
            </div>
          </div>
        </div>
        <button type='submit' class="btn btn-default" >Submit</button>
      </form>
    </div> <!--end of right panel-->


  </div>
  <div class='gradient-hr'></div>
  <div class='footer'>
    <!--hr-->
    <p><閉上眼睛深呼吸,估估出門好時機 All Rights Open></p>
  </div>
</div>
{% endblock %}

{% block "extra_script" %}

$(function () {
$('#datetimepicker1').datetimepicker({
sideBySide: true,
format: "YYYY/MM/DD HH:mm",

{% if time != ''%}defaultDate: "{{time}}" {% endif %}
});
});

$(function()
{
initialize();
{% if type %}$('input[value={{type}}]').prop('checked',true){% endif %}


{% if time != ''%}
var getdate =  Date.parse("{{time}}");
var fd = Date.parse("2015/05/20");
if(getdate > fd )
{
$('#weather').attr("src", "{% static 'jampredict/images/rainny.png'%}");
}

$('#weather').removeClass('hidden');

{% endif %}
});


$('#btn1').click(function(){
initialize();
});

$("#cbx1, #cbx2").change(function() {
initialize();
});


var gridh = 0.0035, gridw = 0.004;
function initialize() {

var color_map = {{cmap|safe}}
var map = new google.maps.Map(document.getElementById('map_canvas'), {
zoom: 13,
center: new google.maps.LatLng(25.050208, 121.544128),
mapTypeId: google.maps.MapTypeId.TERRAIN
});
for(i=0;i<40;i++)
for(j=0;j<40;j++)
{
add_rect(map,24.988391 + gridh*i,121.473983+gridw*j, color_map[i][j]);
}
var points = $.parseJSON('{{data|safe}}');
if($('#cbx1')[0].checked)
{
for(var i in points)
{

add_mark(map, points[i]);
}
}


if($('#cbx2')[0].checked)
{
var viewinfo_points = $.parseJSON('{{viewinfo|safe}}');
for(var i in viewinfo_points)
{

add_mark_viewinfo(map, viewinfo_points[i]);
}
}

}

var image = '{% static "jampredict/images/icon_cam.png" %}'

function add_mark(map, point)
{
var myLatlng = new google.maps.LatLng(point['lat'], point['lon']);
var marker = new google.maps.Marker({
position: myLatlng,
map: map,
icon: image,
title: point['SectionId'] + ": " + point['AvgSpd']
});
}

var image_view_info = '{% static "jampredict/images/icon_touristattraction.png" %}'
function add_mark_viewinfo(map, point)
{
var myLatlng = new google.maps.LatLng(point['latitude'], point['longitude']);
var marker = new google.maps.Marker({
position: myLatlng,
map: map,
icon: image_view_info,
title: point['stitle']
});
}


function add_rect(map, lat, lon, color_level) 
{
if(color_level == -1)
return;

if(color_level < 5)
color_level = 5;
else if( color_level > 15 )
color_level = 15;

var g =Math.floor((255 * (color_level-5)) / 11);
var r =Math.floor((255*(11-(color_level-5))) /11);
//ctx.fillStyle = 'rgba('+r+','+g+',0,0.5)'
var rectangle = new google.maps.Rectangle({
strokeColor: '#FF0000',
strokeOpacity: 0.8,
strokeWeight: 0,
//fillColor: '#FF0000',
fillColor: 'rgb('+r+','+g+',0)',
fillOpacity: 0.7,
map: map,
bounds: new google.maps.LatLngBounds(
//new google.maps.LatLng(33.671068, -116.25128),
// new google.maps.LatLng(33.685282, -116.233942))
new google.maps.LatLng(lat, lon),
new google.maps.LatLng(lat +gridh, lon+gridw))
});
}
{% endblock %}

mysite/jampredict/templates/jampredict/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  <style type="text/css" media="screen">
    body { background:#eee; margin:1em; text-align:center; }
    canvas { display:block; margin:1em auto; background:#fff; border:1px solid #ccc }
  </style>
  </head>
  <body>
    <h1>Hello, world!</h1>
    <!--img src="http://maps.googleapis.com/maps/api/staticmap?center=捷運忠孝復興&zoom=13&scale=2&size=640x500&maptype=roadmap&format=png&visual_refresh=true" alt="Google Map of 捷運忠孝復興"-->
    <canvas id='canvas'></canvas>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
<script type="text/javascript" charset="utf-8">
  var canvas = document.getElementsByTagName('canvas')[0];
  canvas.width = 640; canvas.height = 500;
  var gkhead = new Image;
  var ball   = new Image;
  window.onload = function(){   
    var ctx = canvas.getContext('2d');
    trackTransforms(ctx);
    //ctx.scale(0.5,0.5);
    var arr = new Array(32)
    for(var i = 0; i< 32;i++)
    {
      arr[i] = new Array(25)
    }

    for(var i = 0 ;i < 32; i++)
      for(var j = 0 ; j< 25; j++)
      {
        var n = Math.floor((Math.random() * 100) + 1);
        arr[i][j] = n;
      }
    
    function redraw(){
      // Clear the entire canvas
      var p1 = ctx.transformedPoint(0,0);
      var p2 = ctx.transformedPoint(canvas.width,canvas.height);
      ctx.clearRect(p1.x,p1.y,p2.x-p1.x,p2.y-p1.y);

      // Alternatively:
      // ctx.save();
      // ctx.setTransform(1,0,0,1,0,0);
      // ctx.clearRect(0,0,canvas.width,canvas.height);
      // ctx.restore();
      ctx.drawImage(gkhead,0,0,640,500);

      
      for(var i = 0 ;i <32; i++)
        for(var j = 0 ; j< 25; j++)
        {
          var n = arr[i][j];
          var r =Math.floor((255 * n) / 100);
          var g =Math.floor((255*(100-n)) /100);
          ctx.fillStyle = 'rgba('+r+','+g+',0,0.5)'
          ctx.fillRect(i*20, j*20, 20, 20);
        }
    }
    redraw();
    
    var lastX=canvas.width/2, lastY=canvas.height/2;
    var dragStart,dragged;
    canvas.addEventListener('mousedown',function(evt){
      document.body.style.mozUserSelect = document.body.style.webkitUserSelect = document.body.style.userSelect = 'none';
      lastX = evt.offsetX || (evt.pageX - canvas.offsetLeft);
      lastY = evt.offsetY || (evt.pageY - canvas.offsetTop);
      dragStart = ctx.transformedPoint(lastX,lastY);
      dragged = false;
    },false);
    canvas.addEventListener('mousemove',function(evt){
      lastX = evt.offsetX || (evt.pageX - canvas.offsetLeft);
      lastY = evt.offsetY || (evt.pageY - canvas.offsetTop);
      dragged = true;
      if (dragStart){
        var pt = ctx.transformedPoint(lastX,lastY);
        ctx.translate(pt.x-dragStart.x,pt.y-dragStart.y);
        redraw();
      }
    },false);
    canvas.addEventListener('mouseup',function(evt){
      dragStart = null;
      if (!dragged) zoom(evt.shiftKey ? -1 : 1 );
    },false);

    var scaleFactor = 1.05;
    var zoom = function(clicks){
      var pt = ctx.transformedPoint(lastX,lastY);
      ctx.translate(pt.x,pt.y);
      var factor = Math.pow(scaleFactor,clicks);
      console.log(factor)
      ctx.scale(factor,factor);
      ctx.translate(-pt.x,-pt.y);
      redraw();
    }

    var handleScroll = function(evt){
      var delta = evt.wheelDelta ? evt.wheelDelta/40 : evt.detail ? -evt.detail : 0;
      if (delta) zoom(delta);
      return evt.preventDefault() && false;
    };
    canvas.addEventListener('DOMMouseScroll',handleScroll,false);
    canvas.addEventListener('mousewheel',handleScroll,false);
  };
  gkhead.src = 'http://maps.googleapis.com/maps/api/staticmap?center=捷運忠孝復興&zoom=13&scale=2&size=640x500&maptype=roadmap&format=png&visual_refresh=true';
  ball.src   = 'http://phrogz.net/tmp/alphaball.png';
  
  // Adds ctx.getTransform() - returns an SVGMatrix
  // Adds ctx.transformedPoint(x,y) - returns an SVGPoint
  function trackTransforms(ctx){
    var svg = document.createElementNS("http://www.w3.org/2000/svg",'svg');
    var xform = svg.createSVGMatrix();
    ctx.getTransform = function(){ return xform; };
    
    var savedTransforms = [];
    var save = ctx.save;
    ctx.save = function(){
      savedTransforms.push(xform.translate(0,0));
      return save.call(ctx);
    };
    var restore = ctx.restore;
    ctx.restore = function(){
      xform = savedTransforms.pop();
      return restore.call(ctx);
    };

    var scale = ctx.scale;
    ctx.scale = function(sx,sy){
      xform = xform.scaleNonUniform(sx,sy);
      return scale.call(ctx,sx,sy);
    };
    var rotate = ctx.rotate;
    ctx.rotate = function(radians){
      xform = xform.rotate(radians*180/Math.PI);
      return rotate.call(ctx,radians);
    };
    var translate = ctx.translate;
    ctx.translate = function(dx,dy){
      xform = xform.translate(dx,dy);
      return translate.call(ctx,dx,dy);
    };
    var transform = ctx.transform;
    ctx.transform = function(a,b,c,d,e,f){
      var m2 = svg.createSVGMatrix();
      m2.a=a; m2.b=b; m2.c=c; m2.d=d; m2.e=e; m2.f=f;
      xform = xform.multiply(m2);
      return transform.call(ctx,a,b,c,d,e,f);
    };
    var setTransform = ctx.setTransform;
    ctx.setTransform = function(a,b,c,d,e,f){
      xform.a = a;
      xform.b = b;
      xform.c = c;
      xform.d = d;
      xform.e = e;
      xform.f = f;
      return setTransform.call(ctx,a,b,c,d,e,f);
    };
    var pt  = svg.createSVGPoint();
    ctx.transformedPoint = function(x,y){
      pt.x=x; pt.y=y;
      return pt.matrixTransform(xform.inverse());
    }
  }
</script>

  </body>
</html>

mysite/jampredict/templates/jampredict/test.html
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <style type="text/css">
      html { height: 100% }
      body { height: 100%; margin: 0; padding: 0 }
      #map_canvas { height: 100% }
    </style>
    <script type="text/javascript"
      src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDErdk4TToHeg_NnDslstsd5z5Son5spuE&sensor=FALSE">
    </script>
    <script type="text/javascript">
      function initialize() {
        var mapOptions = {
          center: new google.maps.LatLng(-34.397, 150.644),
          zoom: 8,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("map_canvas"),
            mapOptions);
      }
    </script>
  </head>
  <body onload="initialize()">
    <div id="map_canvas" style="width:100%; height:100%"></div>
  </body>
</html>